/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClinicalReviewRouteImport } from './routes/clinical-review'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as DrugIntelligenceRouteImport } from './routes/drug-intelligence'
import { Route as EvidenceEngineRouteImport } from './routes/evidence-engine'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as KnowledgeBaseRouteImport } from './routes/knowledge-base'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MedicalResearchRouteImport } from './routes/medical-research'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicalReviewRoute = ClinicalReviewRouteImport.update({
  id: '/clinical-review',
  path: '/clinical-review',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const DrugIntelligenceRoute = DrugIntelligenceRouteImport.update({
  id: '/drug-intelligence',
  path: '/drug-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceEngineRoute = EvidenceEngineRouteImport.update({
  id: '/evidence-engine',
  path: '/evidence-engine',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeBaseRoute = KnowledgeBaseRouteImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalResearchRoute = MedicalResearchRouteImport.update({
  id: '/medical-research',
  path: '/medical-research',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clinical-review': typeof ClinicalReviewRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/drug-intelligence': typeof DrugIntelligenceRoute
  '/evidence-engine': typeof EvidenceEngineRoute
  '/history': typeof HistoryRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/mcp': typeof McpRoute
  '/medical-research': typeof MedicalResearchRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clinical-review': typeof ClinicalReviewRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/drug-intelligence': typeof DrugIntelligenceRoute
  '/evidence-engine': typeof EvidenceEngineRoute
  '/history': typeof HistoryRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/mcp': typeof McpRoute
  '/medical-research': typeof MedicalResearchRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clinical-review': typeof ClinicalReviewRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/drug-intelligence': typeof DrugIntelligenceRoute
  '/evidence-engine': typeof EvidenceEngineRoute
  '/history': typeof HistoryRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/mcp': typeof McpRoute
  '/medical-research': typeof MedicalResearchRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clinical-review'
    | '/diagnostics'
    | '/drug-intelligence'
    | '/evidence-engine'
    | '/history'
    | '/knowledge-base'
    | '/mcp'
    | '/medical-research'
    | '/.well-known/oauth-protected-resource'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clinical-review'
    | '/diagnostics'
    | '/drug-intelligence'
    | '/evidence-engine'
    | '/history'
    | '/knowledge-base'
    | '/mcp'
    | '/medical-research'
    | '/.well-known/oauth-protected-resource'
  id:
    | '__root__'
    | '/'
    | '/clinical-review'
    | '/diagnostics'
    | '/drug-intelligence'
    | '/evidence-engine'
    | '/history'
    | '/knowledge-base'
    | '/mcp'
    | '/medical-research'
    | '/.well-known/oauth-protected-resource'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClinicalReviewRoute: typeof ClinicalReviewRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  DrugIntelligenceRoute: typeof DrugIntelligenceRoute
  EvidenceEngineRoute: typeof EvidenceEngineRoute
  HistoryRoute: typeof HistoryRoute
  KnowledgeBaseRoute: typeof KnowledgeBaseRoute
  McpRoute: typeof McpRoute
  MedicalResearchRoute: typeof MedicalResearchRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinical-review': {
      id: '/clinical-review'
      path: '/clinical-review'
      fullPath: '/clinical-review'
      preLoaderRoute: typeof ClinicalReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drug-intelligence': {
      id: '/drug-intelligence'
      path: '/drug-intelligence'
      fullPath: '/drug-intelligence'
      preLoaderRoute: typeof DrugIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence-engine': {
      id: '/evidence-engine'
      path: '/evidence-engine'
      fullPath: '/evidence-engine'
      preLoaderRoute: typeof EvidenceEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-base': {
      id: '/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof KnowledgeBaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-research': {
      id: '/medical-research'
      path: '/medical-research'
      fullPath: '/medical-research'
      preLoaderRoute: typeof MedicalResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClinicalReviewRoute: ClinicalReviewRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  DrugIntelligenceRoute: DrugIntelligenceRoute,
  EvidenceEngineRoute: EvidenceEngineRoute,
  HistoryRoute: HistoryRoute,
  KnowledgeBaseRoute: KnowledgeBaseRoute,
  McpRoute: McpRoute,
  MedicalResearchRoute: MedicalResearchRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
